kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "bison-demo"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/donovanmuller/bison-bank.git"
  triggers:
    - type: "GitHub"
      github:
        secret: "bison"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy: {}
