apiVersion: v1
kind: Template
metadata:
  name: "bison-bank"
  annotations:
    artifactId: "bison-bank"
    description: "A Bison demo"
    tags: bison,service
labels:
   template: bison-demo
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "bison-bank"
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "springboot-maven3-centos"
    spec:
      tags:
        - from:
          kind: DockerImage
          name: codecentric/springboot-maven3-centos
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "bison-bank"
      labels:
        name: "bison-bank"
    spec:
      triggers:
        - type: ConfigChange
      source:
        type: Git
        git:
          uri: "https://github.com/donovanmuller/bison-bank.git"
      strategy:
        type: "Source"
        sourceStrategy:
          from:
            kind: "ImageStreamTag"
            name: "springboot-maven3-centos:latest"
      output:
        to:
          kind: ImageStreamTag
          name: "bison-bank:latest"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "bison-bank"
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "bison-bank"
            from:
              kind: ImageStreamTag
              name: "bison-bank:latest"
        - type: ConfigChange
      replicas: 1
      selector:
        name: "bison-bank"
      template:
        metadata:
          labels:
            name: "bison-bank"
        spec:
          containers:
            - name: "bison-bank"
              image: "bison-bank"
              ports:
                - name: http
                  containerPort: 8080
              readinessProbe:
                httpGet:
                  path: /info
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 5
              livenessgit Probe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 5
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      name: "bison-bank"
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: http
      selector:
        name: "bison-bank"
      sessionAffinity: ClientIP
  - apiVersion: v1
    kind: Route
    metadata:
      name: "bison-bank"
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
    spec:
      host: bison-bank.openshift.switchbit.io
      to:
        kind: Service
        name: "bison-bank"
      port:
        targetPort: http
